apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdmmesh.fullname" . }}
  labels: {{- include "rdmmesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "rdmmesh.selectorLabels" . | nindent 4 }}
  ports:
    - { name: http,  port: {{ .Values.service.httpPort }},  targetPort: http }
    # admin-порт НЕ публикуется ingress'ом (healthcheck/metrics — internal).
    - { name: admin, port: {{ .Values.service.adminPort }}, targetPort: admin }
